import type { QuestionBankItem, ExamDef, ExamSubmission } from "@/types/dashboard-exams";

/**
 * Shared exam-system mock data (Phase 1, no Supabase project connected
 * yet) — read by both the teacher dashboard (question bank, exam builder,
 * grading) and the student dashboard (sitting exams, viewing results).
 * batchId values match src/lib/mock-data/dashboard-teacher.ts's
 * teacherBatches ("tb-1" = A/L Combined Maths Mon/Wed, "tb-2" = A/L
 * Physics Wed). Student ids match enrolledStudents in the same file —
 * "stu-7" is Sithara Gunasekara, the signed-in demo student (see
 * CURRENT_STUDENT in ./dashboard-student.ts).
 */

export const questionBank: QuestionBankItem[] = [
  {
    id: "q-1",
    text: "A particle moves along a straight line with velocity v = 3t² − 6t. Find the displacement between t = 0 and t = 3 seconds.",
    topic: "Mechanics — Kinematics",
    gradeBand: "12-13",
    batchId: "tb-1",
    type: "essay",
    difficulty: "medium",
    marks: 10,
  },
  {
    id: "q-2",
    text: "State and explain the conditions for equilibrium of a rigid body under three coplanar forces.",
    topic: "Mechanics — Statics",
    gradeBand: "12-13",
    batchId: "tb-1",
    type: "essay",
    difficulty: "easy",
    marks: 8,
  },
  {
    id: "q-3",
    text: "Set up and perform an experiment to determine the focal length of a convex lens using the no-parallax method.",
    topic: "Optics — Lenses",
    gradeBand: "12-13",
    batchId: "tb-2",
    type: "essay",
    difficulty: "medium",
    marks: 12,
  },
  {
    id: "q-4",
    text: "Two capacitors of 4 μF and 6 μF are connected in series then in parallel. Compare the equivalent capacitance in both cases.",
    topic: "Electricity — Capacitance",
    gradeBand: "12-13",
    batchId: "tb-2",
    type: "essay",
    difficulty: "hard",
    marks: 10,
  },
  {
    id: "q-5",
    text: "Derive the expression for the period of a simple pendulum undergoing small oscillations.",
    topic: "Waves — Simple Harmonic Motion",
    gradeBand: "12-13",
    batchId: "tb-2",
    type: "essay",
    difficulty: "medium",
    marks: 8,
  },
  {
    id: "q-6",
    text: "Which of the following is the SI unit of force?",
    topic: "Mechanics — Units",
    gradeBand: "12-13",
    batchId: "tb-1",
    type: "mcq",
    difficulty: "easy",
    marks: 1,
    options: [
      { id: "q6-o1", text: "Newton" },
      { id: "q6-o2", text: "Joule" },
      { id: "q6-o3", text: "Watt" },
      { id: "q6-o4", text: "Pascal" },
    ],
    correctOptionId: "q6-o1",
  },
  {
    id: "q-7",
    text: "The derivative of sin(x) with respect to x is:",
    topic: "Calculus — Differentiation",
    gradeBand: "12-13",
    batchId: "tb-1",
    type: "mcq",
    difficulty: "medium",
    marks: 1,
    options: [
      { id: "q7-o1", text: "cos(x)" },
      { id: "q7-o2", text: "−cos(x)" },
      { id: "q7-o3", text: "sin(x)" },
      { id: "q7-o4", text: "−sin(x)" },
    ],
    correctOptionId: "q7-o1",
  },
  {
    id: "q-8",
    text: "A body moving with constant velocity has:",
    topic: "Mechanics — Kinematics",
    gradeBand: "12-13",
    batchId: "tb-1",
    type: "mcq",
    difficulty: "easy",
    marks: 1,
    options: [
      { id: "q8-o1", text: "Zero acceleration" },
      { id: "q8-o2", text: "Constant acceleration" },
      { id: "q8-o3", text: "Increasing acceleration" },
      { id: "q8-o4", text: "Zero velocity" },
    ],
    correctOptionId: "q8-o1",
  },
  {
    id: "q-9",
    text: "The equivalent resistance of two 4 Ω resistors connected in parallel is:",
    topic: "Electricity — Resistance",
    gradeBand: "12-13",
    batchId: "tb-2",
    type: "mcq",
    difficulty: "medium",
    marks: 1,
    options: [
      { id: "q9-o1", text: "2 Ω" },
      { id: "q9-o2", text: "4 Ω" },
      { id: "q9-o3", text: "8 Ω" },
      { id: "q9-o4", text: "1 Ω" },
    ],
    correctOptionId: "q9-o1",
  },
  {
    id: "q-10",
    text: "Which phenomenon best demonstrates the wave nature of light?",
    topic: "Optics — Wave Nature",
    gradeBand: "12-13",
    batchId: "tb-2",
    type: "mcq",
    difficulty: "medium",
    marks: 1,
    options: [
      { id: "q10-o1", text: "Diffraction" },
      { id: "q10-o2", text: "Reflection" },
      { id: "q10-o3", text: "Refraction only" },
      { id: "q10-o4", text: "Absorption" },
    ],
    correctOptionId: "q10-o1",
  },
  {
    id: "q-11",
    text: "The speed of light in vacuum is approximately:",
    topic: "Optics — Light",
    gradeBand: "12-13",
    batchId: "tb-2",
    type: "mcq",
    difficulty: "easy",
    marks: 1,
    options: [
      { id: "q11-o1", text: "3 × 10⁸ m/s" },
      { id: "q11-o2", text: "3 × 10⁶ m/s" },
      { id: "q11-o3", text: "3 × 10⁵ m/s" },
      { id: "q11-o4", text: "3 × 10¹⁰ m/s" },
    ],
    correctOptionId: "q11-o1",
  },
  {
    id: "q-12",
    text: "In simple harmonic motion, the restoring force is proportional to the:",
    topic: "Waves — Simple Harmonic Motion",
    gradeBand: "12-13",
    batchId: "tb-2",
    type: "mcq",
    difficulty: "medium",
    marks: 1,
    options: [
      { id: "q12-o1", text: "Displacement" },
      { id: "q12-o2", text: "Velocity" },
      { id: "q12-o3", text: "Acceleration" },
      { id: "q12-o4", text: "Time elapsed" },
    ],
    correctOptionId: "q12-o1",
  },
];

export const examDefs: ExamDef[] = [
  {
    id: "e-1",
    title: "Mechanics Unit Test — Term 2",
    batchId: "tb-1",
    gradeBand: "12-13",
    durationMin: 90,
    scheduledAt: "10 Aug 2026",
    questionIds: ["q-1", "q-6", "q-7", "q-8"],
    examType: "mixed",
    status: "open",
  },
  {
    id: "e-2",
    title: "Waves & Optics Quiz",
    batchId: "tb-2",
    gradeBand: "12-13",
    durationMin: 45,
    scheduledAt: "28 Jul 2026",
    questionIds: ["q-10", "q-11", "q-12", "q-9"],
    examType: "mcq",
    status: "closed",
  },
  {
    id: "e-3",
    title: "2026 A/L Model Exam — Paper I",
    batchId: "tb-1",
    gradeBand: "12-13",
    durationMin: 180,
    scheduledAt: "30 Aug 2026",
    questionIds: ["q-1", "q-2", "q-6", "q-7", "q-8"],
    examType: "mixed",
    status: "upcoming",
  },
];

export const examSubmissions: ExamSubmission[] = [
  {
    id: "sub-1",
    examId: "e-1",
    studentId: "stu-1",
    studentName: "Nimali Perera",
    state: "submitted",
    startedAt: "10 Aug 2026, 5:05 PM",
    submittedAt: "10 Aug 2026, 6:38 PM",
    answers: { "q-6": "q6-o1", "q-7": "q7-o1", "q-8": "q8-o2" },
    essayFiles: ["nimali-mechanics-sheet1.jpg", "nimali-mechanics-sheet2.jpg"],
    autoScore: 2,
    maxScore: 13,
  },
  {
    id: "sub-2",
    examId: "e-1",
    studentId: "stu-3",
    studentName: "Tharushi Fernando",
    state: "graded",
    startedAt: "9 Aug 2026, 7:50 PM",
    submittedAt: "9 Aug 2026, 8:15 PM",
    answers: { "q-6": "q6-o1", "q-7": "q7-o1", "q-8": "q8-o1" },
    essayFiles: ["tharushi-mechanics-sheet1.jpg"],
    autoScore: 3,
    maxScore: 13,
    teacherScore: 9,
    feedback: "Very good working shown, just a minor slip in the final step.",
  },
  {
    id: "sub-3",
    examId: "e-1",
    studentId: "stu-6",
    studentName: "Ravindu Bandara",
    state: "not_started",
  },
  {
    id: "sub-4",
    examId: "e-1",
    studentId: "stu-7",
    studentName: "Sithara Gunasekara",
    state: "not_started",
  },
  {
    id: "sub-5",
    examId: "e-2",
    studentId: "stu-2",
    studentName: "Kasun Silva",
    state: "graded",
    startedAt: "28 Jul 2026, 2:30 PM",
    submittedAt: "28 Jul 2026, 3:10 PM",
    answers: { "q-10": "q10-o1", "q-11": "q11-o1", "q-12": "q12-o1", "q-9": "q9-o1" },
    autoScore: 4,
    maxScore: 4,
  },
  {
    id: "sub-6",
    examId: "e-2",
    studentId: "stu-5",
    studentName: "Sanduni Rathnayake",
    state: "graded",
    startedAt: "28 Jul 2026, 2:40 PM",
    submittedAt: "28 Jul 2026, 3:20 PM",
    answers: { "q-10": "q10-o1", "q-11": "q11-o1", "q-12": "q12-o2", "q-9": "q9-o1" },
    autoScore: 3,
    maxScore: 4,
  },
];
