import type { Listing } from "@/types/listing";

/**
 * Placeholder data for Phase 1 (no Supabase project connected yet). Shaped
 * exactly like the real query result — see src/types/listing.ts.
 */
export const featuredListings: Listing[] = [
  {
    id: "t-1",
    kind: "teacher",
    name: "Mr. P*** K***",
    masked: true,
    roleLabel: "Individual Teacher · Galle",
    gradeChip: "A/L · Combined Maths",
    location: "Galle",
    online: false,
    gradeBand: "12-13",
    gradeBands: ["12-13"],
    avatarInitials: "P***",
    rating: 4.9,
    reviewCount: 128,
    subjects: ["Combined Maths", "Physics"],
    price: { amount: 1500, currency: "LKR", interval: "hr" },
    href: "/teacher/t-1",
  },
  {
    id: "t-2",
    kind: "teacher",
    name: "Mrs. S*** F***",
    masked: true,
    roleLabel: "Individual Teacher · Matara · Online",
    gradeChip: "Grade 6–9 · Science",
    location: "Matara",
    online: true,
    gradeBand: "6-9",
    gradeBands: ["6-9"],
    avatarInitials: "S***",
    rating: 4.8,
    reviewCount: 76,
    subjects: ["Science", "ICT"],
    price: { amount: 6000, currency: "LKR", interval: "mo" },
    href: "/teacher/t-2",
  },
  {
    id: "t-3",
    kind: "teacher",
    name: "Dr. D*** W***",
    masked: true,
    roleLabel: "Campus Lecturer · Colombo · Online",
    gradeChip: "Campus · Computer Science",
    location: "Colombo",
    online: true,
    gradeBand: "campus",
    gradeBands: ["campus"],
    avatarInitials: "D***",
    rating: 5.0,
    reviewCount: 34,
    subjects: ["Data Structures", "Algorithms"],
    price: { amount: 2500, currency: "LKR", interval: "hr" },
    href: "/teacher/t-3",
  },
  {
    id: "c-1",
    kind: "class",
    name: "Horizon Learning Institute",
    masked: false,
    roleLabel: "Class · 6 teachers · Matara",
    gradeChip: "Institute · O/L All subjects",
    location: "Matara",
    online: false,
    gradeBand: "10-11",
    gradeBands: ["10-11"],
    avatarInitials: "🏫",
    rating: 4.7,
    reviewCount: 211,
    subjects: ["Maths", "English", "Science"],
    price: { amount: 1200, currency: "LKR", interval: "hr", fromPrice: true },
    href: "/class/c-1",
  },
  {
    id: "t-4",
    kind: "teacher",
    name: "Ms. N*** R***",
    masked: true,
    roleLabel: "Individual Teacher · Tangalle",
    gradeChip: "Grade 1–5 · All subjects",
    location: "Tangalle",
    online: false,
    gradeBand: "1-5",
    gradeBands: ["1-5"],
    avatarInitials: "N***",
    rating: 4.9,
    reviewCount: 52,
    subjects: ["Primary — All subjects"],
    price: { amount: 1000, currency: "LKR", interval: "hr" },
    href: "/teacher/t-4",
  },
  {
    id: "c-2",
    kind: "class",
    name: "Apex Campus Academy",
    masked: false,
    roleLabel: "Class · 4 lecturers · Colombo · Online",
    gradeChip: "Institute · Campus prep",
    location: "Colombo",
    online: true,
    gradeBand: "campus",
    gradeBands: ["campus"],
    avatarInitials: "🏫",
    rating: 4.6,
    reviewCount: 88,
    subjects: ["Engineering Maths", "Statistics"],
    price: { amount: 3000, currency: "LKR", interval: "hr", fromPrice: true },
    href: "/class/c-2",
  },
];

/**
 * Wider result pool for the /teachers search page — a superset of
 * featuredListings (which stays a small curated subset for the homepage).
 */
export const allListings: Listing[] = [
  ...featuredListings,
  {
    id: "t-5",
    kind: "teacher",
    name: "Mr. R*** J***",
    masked: true,
    roleLabel: "Individual Teacher · Kandy · Online",
    gradeChip: "O/L · Mathematics",
    location: "Kandy",
    online: true,
    gradeBand: "10-11",
    gradeBands: ["10-11"],
    avatarInitials: "R***",
    rating: 4.7,
    reviewCount: 61,
    subjects: ["Mathematics"],
    price: { amount: 1200, currency: "LKR", interval: "hr" },
    href: "/teacher/t-5",
  },
  {
    id: "t-6",
    kind: "teacher",
    name: "Mrs. C*** P***",
    masked: true,
    roleLabel: "Individual Teacher · Negombo",
    gradeChip: "Grade 6–9 · English",
    location: "Negombo",
    online: false,
    gradeBand: "6-9",
    gradeBands: ["6-9"],
    avatarInitials: "C***",
    rating: 4.9,
    reviewCount: 40,
    subjects: ["English"],
    price: { amount: 1300, currency: "LKR", interval: "hr" },
    href: "/teacher/t-6",
  },
  {
    id: "c-3",
    kind: "class",
    name: "Seaside Tuition Circle",
    masked: false,
    roleLabel: "Class · 3 teachers · Galle · Online",
    gradeChip: "Institute · A/L Science stream",
    location: "Galle",
    online: true,
    gradeBand: "12-13",
    gradeBands: ["12-13"],
    avatarInitials: "🏫",
    rating: 4.5,
    reviewCount: 29,
    subjects: ["Physics", "Chemistry", "Biology"],
    price: { amount: 1800, currency: "LKR", interval: "hr", fromPrice: true },
    href: "/class/c-3",
  },
  {
    id: "t-7",
    kind: "teacher",
    name: "Ms. A*** S***",
    masked: true,
    roleLabel: "Individual Teacher · Kurunegala · Online",
    gradeChip: "All ages · Spoken English",
    location: "Kurunegala",
    online: true,
    gradeBand: "10-11",
    gradeBands: ["10-11"],
    avatarInitials: "A***",
    rating: 4.8,
    reviewCount: 47,
    subjects: ["Spoken English", "English"],
    price: { amount: 1000, currency: "LKR", interval: "hr" },
    href: "/teacher/t-7",
  },
];
